### PR TITLE
ci: update golang version to go1.23

### LINKED ISSUE #1030: update openshift-ci go version to 1.23
since after the bundle creation we test it by running `crc` with the bundle, the job clones crc repo and builds it from source, but currently `snc-microshift` is failing with the following error:

```
GOARCH=arm64 GOOS=darwin go build -tags "containers_image_openpgp" -ldflags="-X github.com/crc-org/crc/v2/pkg/crc/version.crcVersion=2.48.0 -X github.com/crc-org/crc/v2/pkg/crc/version.ocpVersion=4.18.1 -X github.com/crc-org/crc/v2/pkg/crc/version.okdVersion=4.15.0-0.okd-2024-02-23-163410 -X github.com/crc-org/crc/v2/pkg/crc/version.microshiftVersion=4.18.1 -X github.com/crc-org/crc/v2/pkg/crc/version.commitSha=3601e6 " -o out/macos-arm64/crc  ./cmd/crc
go: go.mod requires go >= 1.23.0 (running go 1.22.9; GOTOOLCHAIN=local) 
```

job full logs: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/crc-org_snc/980/pull-ci-crc-org-snc-master-e2e-microshift/1901599252476334080

we'll probably need to update the image references in:

https://github.com/crc-org/snc/blob/4e0f5e39bc71a3297b950b097b3e034560f02bb9/ci_microshift.sh#L21

https://github.com/crc-org/snc/blob/4e0f5e39bc71a3297b950b097b3e034560f02bb9/ci.sh#L61

### PR DESCRIPTION
**Pull request by anjannath**
fixes #1030

### CODE REVIEW

File: ci.sh [hunk 1]
```diff
@@ -58,7 +58,7 @@ sudo systemctl reload NetworkManager
 
 git clone https://github.com/code-ready/crc.git
 pushd crc
-podman run --rm -v ${PWD}:/data:Z registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.22-openshift-4.17 /bin/bash -c "cd /data && make cross"
+podman run --rm -v ${PWD}:/data:Z registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.23-openshift-4.19 /bin/bash -c "cd /data && make cross"
 sudo mv out/linux-amd64/crc /usr/local/bin/
```
Comment (cfergeau) [inline ci.sh:62]: Might be worth moving this to a container image instead of doing it manually and duplicating the logic in 2 places.

**Review by cfergeau — COMMENTED** [review]
Looks like these files are missing from the `update-go-version.sh` script and are not automatically updated at the same time as the other places?
